version: '3.9'

services:
    zpi-web:
        container_name: zpi-web
        #image: ghcr.io/xxx/xxx:latest # use ':latest' for latest version
        pull_policy: always
        ports:
            - '5173:5173'
        networks:
            - zpi-network
networks:
    zpi-network:
        driver: bridge

## tips and tricks
# docker compose -f docker-compose.prod.yml up -d
# docker compose -f docker-compose.prod.yml down
